### ISSUE TITLE
Can't register new account

### ISSUE THREAD

**Issue by gerritvb** [jsomers/lesswrong#1]
Steps taken:
1. Input information here http://lesswrong.com/password in registration pane
2. display: "submitting..."
3. receive email, "To confirm your email address, go to http://lesswrong.com/verifyemail and enter code ___"
4. click link, redirects to http://lesswrong.com/login?dest=%2Fverifyemail (this is the same page as the original registration / login page)
5. there is no field for the verify email code; entering registration information does nothing; 
6. "forgot password" process tells me that my account doesn't exist.

How can I register a new account?

**Comment by jsomers** [comment]
hi @gerritvb this is a fork of the main lesswrong repo that I don't maintain or really use. not sure what the main repo is now, though it used to be github.com/tricycle/lesswrong. good luck!
